[project]
name = "Test of prismAId"
author = "Riccardo Boero"
version = "0.3"

[project.configuration]
input_directory = "../projects/input/test"
results_file_name = "../projects/output/test/output_test"
output_format = "csv"
log_level = "low"
duplication = "no"
cot_justification = "no"
summary = "no"

[project.llm]
[project.llm.1]
provider = "OpenAI"
api_key = ""
model = "gpt-4o-mini"
temperature = 0.001
tpm_limit = 0
rpm_limit = 0

[prompt]
persona = "You are an experienced scientist reviewing scientific literature to map the methods used by other scientists in the field." 
task = "You are asked to map the concepts discussed in a scientific paper attached here."
expected_result = "You should output a JSON object with the following keys and possible values: "
failsafe = "For the key 'historical period studied', provide any relevant period or era mentioned in the document. If the concepts neither are clearly discussed in the document nor they can be deduced from the text, respond with an empty '' value."
definitions = "'Historical data analysis' refers to the examination and interpretation of past observed or modeled data to identify patterns, trends, and insights. 'Forecasting' refers to using models to predict future scenarios or variables of interest. 'Copulas' refer to statistical methods used to join multiple statistical distributions to model their dependencies. 'Regression models' refer to statistical models that utilize linear and nonlinear regression techniques to analyze relationships between variables. 'Clustering' refers to statistical methods for defining groups or patterns of similar data points based on similarities, distances, or multinomial characteristics. 'Bayesian approach' refers to a statistical method that incorporates prior knowledge or beliefs, updating them with new data to form posterior probabilities. 'Geographical scale' refers to the spatial level at which analysis is conducted. 'Historical period studied' refers to the time period of interest in historical data analysis."
example = ""

[review]
[review.1]
key = "historical data analysis"
values = ["yes", "no"]
[review.2]
key = "forecasting"
values = ["yes", "no"]
[review.3]
key = "copulas"
values = ["yes", "no"]
[review.4]
key = "regression models"
values = ["yes", "no"]
[review.5]
key = "clustering"
values = ["yes", "no"]
[review.6]
key = "bayesian approach"
values = ["yes", "no"]
[review.7]
key = "geographical scale"
values = ["world", "continent", "river basin"]
[review.8]
key = "historical period studied"
values = []
