# Use the Just the Docs theme
remote_theme: pmarsceill/just-the-docs

title: prismAId
description: Open Science AI Tools for Systematic, Protocol-Based Literature Reviews.

# Optional settings for GitHub Pages
include:
  - _pages
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - README.md

# Sidebar navigation structure
just_the_docs:
  # Enable or disable the navigation sidebar
  show_sidebar: true

  # Specify the order of the pages in the navigation
  nav_order:
    - Home
    - Readme
    - User Manual
    - Contributing
    - Code of Conduct

# Navigation links
nav:
  home:
    - title: "Home"
      url: "/"
      nav_order: 1
  readme:
    - title: "Readme"
      url: "/README"
      nav_order: 2
  user_manual:
    - title: "User Manual"
      url: "/user_manual/manual"
      nav_order: 3
  contributing:
    - title: "Contributing"
      url: "/CONTRIBUTING"
      nav_order: 4
  code_of_conduct:
    - title: "Code of Conduct"
      url: "/CODE_OF_CONDUCT"
      nav_order: 5

