remote_theme: pmarsceill/just-the-docs
title: prismAId
description: Open Science AI Tools for Systematic, Protocol-Based Literature Reviews.

# Optional settings for GitHub Pages
include:
  - _pages
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md

# Optional navigation links
navigation:
  - name: Home
    link: index.html
  - name: User Manual
    link: user_manual/manual.md
  - name: Contributing
    link: CONTRIBUTING.md
  - name: Code of Conduct
    link: CODE_OF_CONDUCT.md
