site_name: My Project Documentation
theme:
  name: material
nav:
  - Home: index.md
  - User Manual:
      - Manual: user-manual/manual.md
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences
extra_css:
  - css/custom.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
