remote_theme: Open-and-Sustainable/greendoc_theme
title: "prismAId"
description: "Documentation for the prismAId tools"
baseurl: "/prismAId"
url: "https://open-and-sustainable.github.io"
github_repo: "https://github.com/Open-and-Sustainable/prismAId"
logo: "assets/images/prismaid-logo.png"
favicon: "assets/images/prismaid-favicon.ico"
nav_links:
  - name: "Getting Started"
    url: "/getting-started.html"
  - name: "Project Setup"
    url: "/project-setup.html"
  - name: "Prompt Design"
    url: "/prompt-design.html"
  - name: "Advanced Features"
    url: "/advanced-features.html"
  - name: "Open Science"
    url: "/open-science.html"
  - name: "FAQs"
    url: "/faqs.html"
  - name: "For Developers"
    url: "/for-developers.html"

nav_background_color: "#0056b3" # Override nav bar color (darker blue)
nav_hover_color: "#007BFF"      # Override hover color (blue)
nav_link_color: "#ffffff"       # Override link text color (white)
toc-hover-color: "#007BFF"      # Override TOC hover color (blue)