name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install mkdocs
        pip install mkdocs-material
        pip install pygments  # Required for syntax highlighting
        pip install pymdown-extensions  # Required for Arithmatex and superfences extensions

    - name: Copy documentation files
      run: |
        mkdir -p docs/user-manual
        cp README.md docs/index.md
        cp user_manual/manual.md docs/user-manual/manual.md

    - name: Build MkDocs site
      run: mkdocs build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
