name: Register Julia Package to Custom Registry

on:
  push:
    branches:
      - 85-add-package-release-in-julia

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use LocalRegistryAction to Register Package
        uses: ericphanson/LocalRegistryAction.jl@v1
        with:
          registry: 'https://github.com/open-and-sustainable/julia.git'
          registry-name: 'OpenRegistry'
          package-dir: 'julia/PRISMAID'
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_PAT }}
