name: Register Julia Package to Custom Registry

on:
  release:
    types: [created]

jobs:
  update-version-for-julia:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Git
        run: sudo apt-get install git

      - name: Determine Version
        id: versioning
        run: |
          if [[ $GITHUB_REF =~ refs/tags/v* ]]; then
            # If build is triggered by a tag
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            # If build is triggered by a branch push without a tag, use the latest tag from main
            VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
            VERSION=${VERSION#v}  # Strip 'v' prefix if present in tags
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version determined: ${VERSION}"

      - name: Update Project.toml File
        run: |
          sed -i "s/^version = .*/version = \"${{ env.VERSION }}\"/" julia/PRISMAID/Project.toml
        
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin main
          # Check for changes in the Project.toml file
          git add julia/PRISMAID/Project.toml
          if git diff --staged --quiet; then
            echo "No changes detected. Skipping branch creation and pull request."
            exit 0
          fi
          # Create a new branch only if there are changes
          git checkout -b update-version-${GITHUB_RUN_ID}
          git commit -m "Update version to ${{ env.VERSION }}"
          git push -u origin update-version-${GITHUB_RUN_ID}
          # Create Pull Request
          gh pr create --title "Update Julia Package Version" --body "Auto-update version to ${{ env.VERSION }} by CI/CD." --base main --head update-version-${GITHUB_RUN_ID}
          # Automatically merge the PR
          gh pr merge --auto --squash --delete-branch

  register-package:
    runs-on: ubuntu-latest
    needs: [update-version-for-julia]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      # Post Registrator Comment on Issue #85
      - name: Trigger Registrator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment --repo open-and-sustainable/prismaid \
            --body "@JuliaRegistrator register subdir=julia/PRISMAID " \
            85

