name: Register Julia Package to Custom Registry

on:
  push:
    branches:
      - 85-add-package-release-in-julia

jobs:
  register-package:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Julia environment
      - name: Set Up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'

      # Install LocalRegistry.jl
      - name: Install LocalRegistry.jl
        run: julia -e 'using Pkg; Pkg.add("LocalRegistry")'

      # Register the package locally
      - name: Register Package
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_PAT }}
        run: |
          julia -e '
          using LocalRegistry;
          LocalRegistry.register(
              "julia/PRISMAID",
              registry = "OpenRegistry", # Use the name from Registry.toml
              commit = true,
              push = true,
              branch = "main",
              repo = "https://github.com/open-and-sustainable/julia.git"
          )'



