name: Register Julia Package to Custom Registry

on:
  push:
    branches:
      - 85-add-package-release-in-julia

jobs:
  register-package:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install GitHub CLI (if not already available)
      - name: Install GitHub CLI
        run: sudo apt-get install gh

      # Post Registrator Comment on Issue #85
      - name: Trigger Registrator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment --repo open-and-sustainable/prismaid \
            --body "@JuliaRegistrator register subdir=julia/PRISMAID branch=85-add-package-release-in-julia" \
            85

