name: Build and Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: Build binaries for multiple platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        include:
          - goos: linux
            extension: ""
          - goos: windows
            extension: ".exe"
          - goos: darwin
            extension: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build binary
        run: |
          mkdir -p bin
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o bin/prismAId_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.extension }} ./cmd/main.go

      - name: Archive binary
        run: |
          zip -j bin/prismAId_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.extension }}.zip bin/prismAId_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.extension }}

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: bin/prismAId_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.extension }}.zip
          asset_name: prismAId_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.extension }}.zip
          asset_content_type: application/zip
  
