name: Temp library building

# Trigger the workflow on push to the main branch and on pull requests
on:
  push:
    branches:
      - 71-r-package-does-not-compile-for-macos-and-windows

jobs:
  build-macos-arm64:
    name: Build macOS Arm64 Shared Library
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build shared library for macOS
        working-directory: sharedlib
        run: |
          go build -buildmode=c-shared -o libprismaid_darwin_arm64.dylib export.go

      - name: Upload macOS shared library artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-shared-library
          path: sharedlib/libprismaid_darwin_arm64.dylib

      - name: Commit and push changes
        run: |
          cp sharedlib/libprismaid_darwin_arm64.dylib inst/libs/macos/libprismaid_darwin_arm64.dylib
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout ${GITHUB_REF#refs/heads/}
          git pull --no-rebase origin ${GITHUB_REF#refs/heads/}
          git add inst/libs/macos/libprismaid_darwin_arm64.dylib
          git diff --staged --quiet || (git commit -m "Update MacOS lib." && git push)