name: Test of Versioning and Build

on:
  push:
    branches:
    - 41-add-pipeline-to-publish-prismaid-as-r-module

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessary to fetch all history for tags

      - name: Install Git
        run: sudo apt-get install git

      - name: Determine Version
        id: versioning
        run: |
          if [[ $GITHUB_REF =~ refs/tags/v* ]]; then
            # If build is triggered by a tag
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            # If build is triggered by a branch push without a tag, use the latest tag from main
            VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
            VERSION=${VERSION#v}  # Strip 'v' prefix if present in tags
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version determined: ${VERSION}"

      - name: Update DESCRIPTION File
        run: |
          sed -i "s/^Version:.*/Version: ${{ env.VERSION }}/" DESCRIPTION

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add DESCRIPTION
          git diff --staged --quiet || (git commit -m "Update version to ${{ env.VERSION }}" && git push)
