name: Test of Versioning and Build

on:
  push:
    branches:
      - 41-add-pipeline-to-publish-prismaid-as-r-module

jobs:
  build-linux:
    name: Build Linux Shared Library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build shared library for Linux
        working-directory: python
        run: |
          go build -buildmode=c-shared -o package/libprismaid_linux_amd64.so export.go

      - name: Upload Linux shared library artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-shared-library
          path: python/package/libprismaid_linux_amd64.so

  set-version-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Dependencies
        run: |
          Rscript -e "install.packages(c('devtools', 'desc'), repos='http://cran.rstudio.com/')"

      - name: Extract Version from Tag
        id: extract_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}  # Removes 'refs/tags/' prefix
          echo "Tag detected: $TAG"
          VERSION=${TAG#v}  # Removes 'v' prefix
          echo "Version extracted: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update DESCRIPTION Version
        run: |
          Rscript -e "library(desc); desc_file <- desc::desc(file = 'r/prismaid/DESCRIPTION'); desc_file$set_version(Sys.getenv('VERSION')); desc::desc_write(desc_file, file = 'r/prismaid/DESCRIPTION')"

      - name: Build R Package
        run: |
          Rscript -e "devtools::build('r/prismaid')"

      - name: Upload Built Package
        uses: actions/upload-artifact@v3
        with:
          name: prismaid_${{ env.VERSION }}.tar.gz
          path: r/prismaid_*.tar.gz
